{"uid":"33c5dd8516699504","name":"test_successful_login","fullName":"tests.test_home#test_successful_login","historyId":"e4314461c2d18f3e0f88ff8c6a7a33f1","time":{"start":1717884463350,"stop":1717884463350,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"eaefebe892b22dce5a2d15a791edc5e6\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1717884460231,"stop":1717884460248,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"chrome_browser","time":{"start":1717884463350,"stop":1717884463669,"duration":319},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"logged_in_test","time":{"start":1717884463669,"stop":1717884463669,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 35, in logged_in_test\n    user = setup_test_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 44, in setup_test_user\n    user = get_random_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 44, in get_random_user\n    username = generate_username()\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 28, in generate_username\n    username = fake.user_name()\n               ^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"eaefebe892b22dce5a2d15a791edc5e6\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","steps":[],"attachments":[{"uid":"b6c7f901d2af7c0c","name":"log","source":"b6c7f901d2af7c0c.txt","type":"text/plain","size":355}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"chrome_browser::0","time":{"start":1717884463679,"stop":1717884463736,"duration":57},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_home"},{"name":"host","value":"fv-az1055-767"},{"name":"thread","value":"3459-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_home"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":10,"unknown":0,"total":13},"items":[{"uid":"ac97483c41b9ac0c","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/8//#testresult/ac97483c41b9ac0c","status":"passed","time":{"start":1717883303445,"stop":1717883303488,"duration":43}},{"uid":"bc81773327d60c85","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/7//#testresult/bc81773327d60c85","status":"broken","statusDetails":"TypeError: Object of type Response is not JSON serializable","time":{"start":1717776860943,"stop":1717776860943,"duration":0}},{"uid":"659b014d520c60ad","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/6//#testresult/659b014d520c60ad","status":"passed","time":{"start":1717766810943,"stop":1717766810979,"duration":36}},{"uid":"13531c5bbbd8a5b4","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/5//#testresult/13531c5bbbd8a5b4","status":"passed","time":{"start":1717765035454,"stop":1717765035491,"duration":37}},{"uid":"1011733e74dd08c2","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/2//#testresult/1011733e74dd08c2","status":"passed","time":{"start":1717612976848,"stop":1717612976887,"duration":39}},{"uid":"c97e22ef28b2ba2e","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/c97e22ef28b2ba2e","status":"passed","time":{"start":1715622182054,"stop":1715622182098,"duration":44}},{"uid":"2e4e574e17cdae22","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/2e4e574e17cdae22","status":"broken","statusDetails":"requests.exceptions.HTTPError: 400 Client Error:  for url: http://localhost:4001/users/signup","time":{"start":1715618612927,"stop":1715618612927,"duration":0}},{"uid":"c74d1de0f4cca2cd","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/26//#testresult/c74d1de0f4cca2cd","status":"passed","time":{"start":1715529069984,"stop":1715529070025,"duration":41}},{"uid":"7fbcfa55506f685","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/25//#testresult/7fbcfa55506f685","status":"passed","time":{"start":1715528277544,"stop":1715528277585,"duration":41}},{"uid":"ba9de5df239d21d4","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/24//#testresult/ba9de5df239d21d4","status":"passed","time":{"start":1715499478227,"stop":1715499478265,"duration":38}},{"uid":"b82477476c6db441","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/23//#testresult/b82477476c6db441","status":"passed","time":{"start":1715498562374,"stop":1715498562411,"duration":37}},{"uid":"fc3e47a4d8e64d4","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/22//#testresult/fc3e47a4d8e64d4","status":"passed","time":{"start":1715498277825,"stop":1715498277868,"duration":43}}]},"tags":[]},"source":"33c5dd8516699504.json","parameterValues":[]}