{"uid":"a34a17981e3612a4","name":"test_autocomplete","fullName":"tests.test_edit#test_autocomplete","historyId":"116b21cd5116ce076d64042c4703a3e3","time":{"start":1717884461703,"stop":1717884461703,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b77d11a923435e391005fbefdb15e018\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1717884460231,"stop":1717884460248,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"chrome_browser","time":{"start":1717884461704,"stop":1717884462851,"duration":1147},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"logged_in_test","time":{"start":1717884462851,"stop":1717884462851,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 35, in logged_in_test\n    user = setup_test_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 44, in setup_test_user\n    user = get_random_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 44, in get_random_user\n    username = generate_username()\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 28, in generate_username\n    username = fake.user_name()\n               ^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b77d11a923435e391005fbefdb15e018\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","steps":[],"attachments":[{"uid":"6593ccb90a644eb","name":"log","source":"6593ccb90a644eb.txt","type":"text/plain","size":1055}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"chrome_browser::0","time":{"start":1717884462897,"stop":1717884462952,"duration":55},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_edit"},{"name":"host","value":"fv-az1055-767"},{"name":"thread","value":"3459-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_edit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":11,"unknown":0,"total":13},"items":[{"uid":"cd01167307856c3","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/8//#testresult/cd01167307856c3","status":"passed","time":{"start":1717883297659,"stop":1717883298329,"duration":670}},{"uid":"408d8da763c135fa","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/7//#testresult/408d8da763c135fa","status":"broken","statusDetails":"TypeError: Object of type Response is not JSON serializable","time":{"start":1717776851536,"stop":1717776851536,"duration":0}},{"uid":"910e126a5efe977f","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/6//#testresult/910e126a5efe977f","status":"passed","time":{"start":1717766804961,"stop":1717766805712,"duration":751}},{"uid":"e713807e20f5bbdc","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/5//#testresult/e713807e20f5bbdc","status":"passed","time":{"start":1717765029393,"stop":1717765030535,"duration":1142}},{"uid":"2060de7bcba01428","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/2//#testresult/2060de7bcba01428","status":"passed","time":{"start":1717612970800,"stop":1717612971602,"duration":802}},{"uid":"32865bb5063005a","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/32865bb5063005a","status":"passed","time":{"start":1715622175915,"stop":1715622176728,"duration":813}},{"uid":"e9d321fe17c5cd29","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/e9d321fe17c5cd29","status":"passed","time":{"start":1715618608356,"stop":1715618609032,"duration":676}},{"uid":"a8e39fc84d737df4","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/26//#testresult/a8e39fc84d737df4","status":"passed","time":{"start":1715529064012,"stop":1715529064735,"duration":723}},{"uid":"b49c565004edae0e","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/25//#testresult/b49c565004edae0e","status":"passed","time":{"start":1715528271441,"stop":1715528272206,"duration":765}},{"uid":"d7f82726832a022","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/24//#testresult/d7f82726832a022","status":"passed","time":{"start":1715499472236,"stop":1715499472948,"duration":712}},{"uid":"40a9be7bac66e42","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/23//#testresult/40a9be7bac66e42","status":"passed","time":{"start":1715498556582,"stop":1715498557248,"duration":666}},{"uid":"e2aeb4b61d17b9db","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/22//#testresult/e2aeb4b61d17b9db","status":"passed","time":{"start":1715498272111,"stop":1715498272772,"duration":661}}]},"tags":[]},"source":"a34a17981e3612a4.json","parameterValues":[]}